### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Eonfge** [pakeke-constructor/PUSH_GAME#1]
Dear @pakeke-constructor, I recently saw your post Reddit's r/linux_gaming, in which you took a fair amount of flak for calling your game `open-source` while it isn't. I won't harp too much on this, instead I wish to offer some help.

I'm a package maintainer over on [Flathub.org](https://www.flathub.org/home) where I maintain a lot of Id Software titles, most of which are open-source. As such, I can give you some pointers on where to look fur license information and what it entails.

## Sources-available
You will not be the first. Video games are mix of technology and art and I respect it if you wish to remain in artistic control. One example to look at is [VVVVVV](https://github.com/TerryCavanagh/VVVVVV), who is also sources available and who even accepted contributions for [a new patch](https://www.pcgamer.com/almost-seven-years-after-its-last-patch-vvvvvv-is-getting-support-for-higher-framerates-and-more/).

Do make sure that you are very open about your game being sources-available. Telling people that it's open-source while its not, is a legal grey area... and it's scummy.

## Open-source with copy-left
This is what Id Software has been doing for 25 years. Their games are published under the [GPL](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) which means that their games have been having a long and happy life, and that their games are very archive-friendly. You can play Doom (1993) today without any technical issues because of that decision.

One serious aspect of the GPL, is that it's strong copy-left; i.e. everybody that does something with the code, must also publish his changes under the same GPL license. This protects you (the original creator) from somebody taking your work and modifying it with contributing to your project. Mind you, the GPL does not (financially) discriminate so others will be allowed to sell your game.

### Exclude assets (Optional)
This is what Id Software also does. Their game engine is open source, their game assets are not. This allows everybody to build and iterate on Doom (1993), but somebody still needs to own a legal copy to play it.

### add a CLA (Optional)
The CLA is an extra optional legal document that is really popular with multinationals. You publish your code under a specific license, but every code that others send you, they license under the MIT. This is what [Microsoft](https://cla.opensource.microsoft.com/) and [Google](https://cla.developers.google.com/about/google-individual) do it for example, but VVVVVV also did this so they can include the patches in their closed-source commercial editions. 

## Open-source without copy-left
This brings you in the territory of the [MIT](https://tldrlegal.com/license/mit-license), [BSD](https://tldrlegal.com/license/bsd-3-clause-license-(revised)) and [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) license. These licenses give all freedom to others, without any obligation to pass that freedom on. As you might already guess, this is really popular in the business world but it's perhaps not what you want. 

# Closing words
I would recommend the GPL 3.0, but without the assets. This will allow your game to be properly open-source, with all the legal benefits and ramifications, but it will protect your creative control and artistic vision.

I hope it helps, and if you have any further questions, feel free to ask. I'm no lawyer but this is a topic I have a lot of experience in.

**Comment by pakeke-constructor** [comment]
Thank you very much for the extensive issue and explanation.

I have switched to GPL-3 as my license as per your recommendation.

Thanks for the issue- take it easy :)
